// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlcYH0mhnOvHVvFTBw81Wtxh_WTN3etpc',
    appId: '1:20158930019:web:b0afeb06b9e2189fc32c56',
    messagingSenderId: '20158930019',
    projectId: 'saisisse-5d854',
    authDomain: 'saisisse-5d854.firebaseapp.com',
    storageBucket: 'saisisse-5d854.firebasestorage.app',
    measurementId: 'G-XXK8LZDWK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmGnzwyH_2A6k2DezZHInBk1Itp0YG9Gs',
    appId: '1:20158930019:android:ab7eb0917ed3eab5c32c56',
    messagingSenderId: '20158930019',
    projectId: 'saisisse-5d854',
    storageBucket: 'saisisse-5d854.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOKv2vTy5YCi0qcYda5mF0br6ZmTLxEhc',
    appId: '1:20158930019:ios:d0c9390c08031f51c32c56',
    messagingSenderId: '20158930019',
    projectId: 'saisisse-5d854',
    storageBucket: 'saisisse-5d854.firebasestorage.app',
    iosBundleId: 'com.example.doanLtdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOKv2vTy5YCi0qcYda5mF0br6ZmTLxEhc',
    appId: '1:20158930019:ios:d0c9390c08031f51c32c56',
    messagingSenderId: '20158930019',
    projectId: 'saisisse-5d854',
    storageBucket: 'saisisse-5d854.firebasestorage.app',
    iosBundleId: 'com.example.doanLtdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlcYH0mhnOvHVvFTBw81Wtxh_WTN3etpc',
    appId: '1:20158930019:web:3b76cb5d72943a05c32c56',
    messagingSenderId: '20158930019',
    projectId: 'saisisse-5d854',
    authDomain: 'saisisse-5d854.firebaseapp.com',
    storageBucket: 'saisisse-5d854.firebasestorage.app',
    measurementId: 'G-VDKX35TJMZ',
  );
}
